### PR TITLE
Merging upstream changes

### PR DESCRIPTION
**Pull request by hanpeter**
Just merging upstream Yahoo's repo changes.

Also, if you think we should just fast-forward merge without creating a merge commit, let me know. That approach will keep the commit history the same up until now.

### CODE REVIEW

**Comment by jib** [comment]
you may want to add what we build off of - if we build master, this might affect us. if we build tags, we're fine

**Comment by hanpeter** [comment]
@jib: Our current production is using `1.3.0.8` release of [Yahoo's source code](https://github.com/yahoo/kafka-manager/tree/1.3.0.8).

**Comment by jib** [comment]
+1

**Comment by paul-krohn** [comment]
👍

**Pull request merged**
